require("plugin-confs.formatter-nvim")
require("plugin-confs.nvim-tree")
require("plugin-confs.telescope")
require("plugin-confs.toggleterm")
require("plugin-confs.gitsigns")
require("plugin-confs.treesitter")
require("plugin-confs.colorizer")
require("plugin-confs.null-ls")
